@startuml

title Usecase Diagram

left to right direction

actor Sportsman

rectangle Software {

    usecase (pay the bill)
    usecase (authorization)

   :Sportsman: -- (pay the bill)
   (pay the bill) .> (authorization) : include
}

@enduml
